import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {
	SidebarInset,
	SidebarProvider,
	SidebarTrigger,
} from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";
import { headers } from "next/headers";
import path from "path";
import { Sidebar } from "lucide-react";
import MainContaienr from "@/components/layout/main/main-container";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const headersList = await headers();
	const pathname = headersList.get("x-current-path") || "";

	return (
		<html lang="en" suppressHydrationWarning>
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<SidebarProvider>
					<AppSidebar currentPath={pathname} />
					<main className="flex flex-1 flex-col gap-4 p-4 pt-0 w-full h-screen">
						<div className="flex gap-3 items-center">
							<SidebarTrigger />
						</div>
						<MainContaienr>{children}</MainContaienr>
					</main>
				</SidebarProvider>
			</body>
		</html>
	);
}
